### ISSUE TITLE
[Infrastructure] Flaky tests

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgames/FreeBoardGames.org#420]
These two tests **occasionally** fail on Travis.

```
FAIL tests/room/[gameCode]/[roomID]/Room.test.tsx (37.391s)
  ● Room Lobby › should start the game if room is full
    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
      145 |   });
      146 | 
    > 147 |   it('should start the game if room is full', async () => {
          |   ^
      148 |     useRouter.mockImplementation(() => ({
      149 |       query: { gameCode: 'chess', roomID: 'fooroom' },
      150 |     }));
      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/room/[gameCode]/[roomID]/Room.test.tsx:147:3)
      at Object.<anonymous> (tests/room/[gameCode]/[roomID]/Room.test.tsx:11:1)
  ● Room Lobby › should start the game if room is full
    expect(element).toBeInTheDocument()
    element could not be found in the document
      174 |     );
      175 |     // Game starts:
    > 176 |     expect(await wrapper.findByText('Connecting...')).toBeInTheDocument();
          |                                                       ^
      177 |   });
      178 | 
      179 |   it('should update metadata', async () => {
      at Object.<anonymous> (tests/room/[gameCode]/[roomID]/Room.test.tsx:176:55)

```

**Comment by jasonharrison** [comment]
Issue no longer exists due to changes to Room.tsx
